#!/usr/bin/env python3
"""Development-time generator for the offline IANA Link Relation Types registry.

Reads the fixed CSV snapshot ``testdata/iana/link-relations.csv`` and writes a
deterministic MoonBit source file ``generated_relations.mbt``. This is a
DEVELOPMENT-TIME tool only; the MoonBit runtime never calls Python and never
touches the network.

Usage:
    python scripts/import_iana_relations.py            # regenerate from snapshot
    python scripts/import_iana_relations.py --refresh  # download a fresh CSV and
                                                       # update SOURCE.json first

Offline by default. ``--refresh`` is the explicit opt-in for a network fetch.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "testdata" / "iana" / "link-relations.csv"
SOURCE_PATH = ROOT / "testdata" / "iana" / "SOURCE.json"
OUT_PATH = ROOT / "generated_relations.mbt"

IANA_URL = "https://www.iana.org/assignments/link-relations/link-relations-1.csv"


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _moon_escape(s: str) -> str:
    """Escape a string for a MoonBit double-quoted literal."""
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    s = s.replace("\r", " ").replace("\n", " ")
    s = s.replace("\t", " ")
    return s


def load_csv() -> list[dict[str, str]]:
    rows = []
    with open(CSV_PATH, "r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            rows.append(
                {
                    "name": row.get("Relation Name", ""),
                    "description": row.get("Description", ""),
                    "reference": row.get("Reference", ""),
                    "notes": row.get("Notes", ""),
                }
            )
    # Names must be non-empty and unique (the registry is keyed by name).
    seen = set()
    for row in rows:
        name = row["name"]
        if not name:
            raise SystemExit("import_iana_relations.py: empty relation name in CSV")
        if name in seen:
            raise SystemExit(f"import_iana_relations.py: duplicate relation name {name!r}")
        seen.add(name)
    return rows


def render(rows: list[dict[str, str]], sha256: str) -> str:
    out = io.StringIO()
    out.write("// generated_relations.mbt — GENERATED FILE.\n")
    out.write("//\n")
    out.write("// This file is generated by scripts/import_iana_relations.py from\n")
    out.write("// testdata/iana/link-relations.csv, an offline snapshot of the IANA\n")
    out.write("// Link Relation Types registry.\n")
    out.write("//\n")
    out.write("// DO NOT EDIT BY HAND. To regenerate:\n")
    out.write("//\n")
    out.write("//     python scripts/import_iana_relations.py\n")
    out.write("//\n")
    out.write("// Source: https://www.iana.org/assignments/link-relations/link-relations-1.csv\n")
    out.write(f"// Snapshot sha256: {sha256}\n")
    out.write("\n")
    out.write("///|\n")
    out.write("/// The IANA Link Relation Types registry entries in the offline\n")
    out.write("/// snapshot, in registry (alphabetical) order.\n")
    out.write("fn generated_relation_data() -> Array[RelationInfo] {\n")
    out.write("  [\n")
    for row in rows:
        name = _moon_escape(row["name"])
        desc = _moon_escape(row["description"])
        ref = _moon_escape(row["reference"])
        notes = _moon_escape(row["notes"])
        # The multi-line form is what `moon fmt` produces for a struct literal,
        # so the generated file stays byte-stable through formatting.
        out.write("    {\n")
        out.write(f'      name: "{name}",\n')
        out.write(f'      description: "{desc}",\n')
        out.write(f'      reference: "{ref}",\n')
        out.write(f'      notes: "{notes}",\n')
        out.write("    },\n")
    out.write("  ]\n")
    out.write("}\n")
    return out.getvalue()


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--refresh",
        action="store_true",
        help="download a fresh CSV from IANA and update SOURCE.json first",
    )
    args = ap.parse_args()

    if args.refresh:
        print(f"Refreshing snapshot from {IANA_URL} ...")
        with urllib.request.urlopen(IANA_URL, timeout=30) as resp:
            data = resp.read()
        CSV_PATH.write_bytes(data)
        digest = _sha256(data)
        records = len(data.decode("utf-8").splitlines()) - 1
        SOURCE_PATH.write_text(
            json.dumps(
                {
                    "name": "IANA Link Relation Types registry snapshot",
                    "source_url": IANA_URL,
                    "retrieved_at": None,  # replaced below
                    "sha256": digest,
                    "record_count": records,
                    "notes": "Offline snapshot used by the offline registry in "
                    "relation_registry.mbt. The MoonBit runtime never accesses "
                    "this URL.",
                },
                indent=2,
                ensure_ascii=False,
            )
            + "\n",
            encoding="utf-8",
        )
        print(f"Wrote {CSV_PATH.name} ({records} records, sha256 {digest})")
        print("Edit retrieved_at in SOURCE.json to the actual retrieval date.")

    rows = load_csv()
    sha256 = _sha256(CSV_PATH.read_bytes())
    out = render(rows, sha256)
    OUT_PATH.write_text(out, encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)} with {len(rows)} entries "
          f"(sha256 {sha256}).")


if __name__ == "__main__":
    main()
