#!/usr/bin/env python3
"""Verifies the integrity of the offline IANA Link Relation Types snapshot.

Checks, without any network access:

  1. The sha256 of testdata/iana/link-relations.csv equals the value recorded
     in testdata/iana/SOURCE.json.
  2. The number of CSV records equals the value recorded in SOURCE.json.
  3. Regenerating generated_relations.mbt from the CSV reproduces the
     checked-in file byte-for-byte (so the checked-in registry data is exactly
     what the snapshot contains).

Exit code 0 on success, 1 on any mismatch. Intended for CI and for
`scripts/verify_all.ps1`.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "testdata" / "iana" / "link-relations.csv"
SOURCE_PATH = ROOT / "testdata" / "iana" / "SOURCE.json"
GENERATED_PATH = ROOT / "generated_relations.mbt"


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _count_records(csv_path: Path) -> int:
    with open(csv_path, "r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        return sum(1 for _ in reader)


def _regenerate(csv_path: Path) -> str:
    """Mirror of scripts/import_iana_relations.py's render(); kept inline so
    the verifier has no dependency on that script's CLI."""
    def escape(s: str) -> str:
        s = s.replace("\\", "\\\\").replace('"', '\\"')
        s = s.replace("\r", " ").replace("\n", " ").replace("\t", " ")
        return s

    rows = []
    with open(csv_path, "r", encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            rows.append(row)

    out = io.StringIO()
    out.write("// generated_relations.mbt — GENERATED FILE.\n")
    out.write("//\n")
    out.write("// This file is generated by scripts/import_iana_relations.py from\n")
    out.write("// testdata/iana/link-relations.csv, an offline snapshot of the IANA\n")
    out.write("// Link Relation Types registry.\n")
    out.write("//\n")
    out.write("// DO NOT EDIT BY HAND. To regenerate:\n")
    out.write("//\n")
    out.write("//     python scripts/import_iana_relations.py\n")
    out.write("//\n")
    out.write("// Source: https://www.iana.org/assignments/link-relations/link-relations-1.csv\n")
    out.write(f"// Snapshot sha256: {_sha256(csv_path.read_bytes())}\n")
    out.write("\n")
    out.write("///|\n")
    out.write("/// The IANA Link Relation Types registry entries in the offline\n")
    out.write("/// snapshot, in registry (alphabetical) order.\n")
    out.write("fn generated_relation_data() -> Array[RelationInfo] {\n")
    out.write("  [\n")
    for row in rows:
        name = escape(row.get("Relation Name", ""))
        desc = escape(row.get("Description", ""))
        ref = escape(row.get("Reference", ""))
        notes = escape(row.get("Notes", ""))
        # Matches scripts/import_iana_relations.py render(): the multi-line
        # form is what `moon fmt` produces for a struct literal.
        out.write("    {\n")
        out.write(f'      name: "{name}",\n')
        out.write(f'      description: "{desc}",\n')
        out.write(f'      reference: "{ref}",\n')
        out.write(f'      notes: "{notes}",\n')
        out.write("    },\n")
    out.write("  ]\n")
    out.write("}\n")
    return out.getvalue()


def main() -> int:
    problems = 0

    source = json.loads(SOURCE_PATH.read_text(encoding="utf-8"))
    expected_sha = source.get("sha256")
    expected_count = source.get("record_count")

    actual_sha = _sha256(CSV_PATH.read_bytes())
    if expected_sha != actual_sha:
        print(f"FAIL sha256 mismatch: SOURCE.json={expected_sha} file={actual_sha}")
        problems += 1
    else:
        print(f"OK   sha256 {actual_sha}")

    actual_count = _count_records(CSV_PATH)
    if expected_count != actual_count:
        print(f"FAIL record_count mismatch: SOURCE.json={expected_count} file={actual_count}")
        problems += 1
    else:
        print(f"OK   record_count {actual_count}")

    rendered = _regenerate(CSV_PATH)
    checked_in = GENERATED_PATH.read_text(encoding="utf-8")
    if rendered != checked_in:
        print(f"FAIL generated_relations.mbt is stale; re-run scripts/import_iana_relations.py")
        problems += 1
    else:
        print(f"OK   generated_relations.mbt is current")

    if problems:
        print(f"{problems} problem(s) found.")
        return 1
    print("IANA snapshot OK.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
